### PR TITLE
WIP: Add root eslint config and scripts to package.json

### LINKED ISSUE #8: ES lint on all modules
## Problem
Add a script that run the eslint on all child modules.

### PR DESCRIPTION
**Pull request by 0x4d**
Closes #8 

## Describe your changes

- Added all required dependencies for eslint
- Added lint scripts that use `.gitignore` to skip `node_modules`

### CODE REVIEW

**Comment by tim-kilian** [comment]
Hmm, are you sure, we want an extra config for this project? I would consider, that we call each es lint in every submodule rather than have a different config for the top level project than the low level projects.

**Comment by 0x4d** [comment]
The aim was to use a single eslint command to lint all projects with the respective configs.
However, I forgot to remove the `"node": true` declaration so that submodule configs are respected.
I also removed the vue rules now as they are not needed.

The only drawback I can see now ist that all eslint plugins that are required by submodules also need to be added to the root package.json.

However, I think this is still the most straightforward way to do this and better than adding another script recursing the directories. It is also the intended ways as described in the [eslint docs](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy). Moreover, it will result in a single report for all modules.

**Comment by tim-kilian** [comment]
> better than adding another script recursing the directories

Hmm, I still dont like the changes. Why should this be better than adding another recursive script? 

Can we do something like this without the need of a config in the top level repositiory?
```
{
  "name": "renew-js",
  "version": "0.1.0",
  "scripts": {
    "postinstall": "node ./scripts/postinstall.js",
    "preinstall": "node ./scripts/preinstall.js",
    "lint": "eslint --ignore-path .gitignore .",
    "lint-fix": "eslint --fix --ignore-path .gitignore ."
  },
  "devDependencies": {
    "eslint": "^5.15.0",
    "eslint-config-renew": "file:eslint-config-renew"
  }
}
```

**Comment by 0x4d** [comment]
> Hmm, I still dont like the changes. Why should this be better than adding another recursive script?

It is less complex, it is the intended way, it presents a summary of all errors, it doesn't need further effort, it is less prone to errors than an individual solution.

> Can we do something like this without the need of a config in the top level repositiory?

You cant just remove the config block.
First, as I said, all plugins that it will encounter in the cascading configs must be loaded from the start.
Secondly, the rules in `renew-js/package.json` are also for directories where no cascading configs are found, like the `scripts/` directory for example ...

**Comment by tim-kilian** [comment]
> You cant just remove the config block.

Why the config block cant be removed? 
Can we keep it simpler? Maybe just the eslint-config-renew?

**Comment by 0x4d** [comment]
> Why the config block cant be removed?

ESLint won't run without it.

> Can we keep it simpler? Maybe just the eslint-config-renew?

It is a minimal config IMO. The renew config should always be used with eslint:recommended and google (see its [readme](https://github.com/renew-js/eslint-config-renew/blob/master/README.md)) and Node and ES6 are configured as they are used in the `scripts/` dir.

**Comment by tim-kilian** [comment]
> It is also the intended ways as described in the eslint docs.

I'll read the docs and give you an extended opion afterwards. Also my `eslint-fix` is reporting 129 problems. This should be fixed before merge.

**Comment by 0x4d** [comment]
> I'll read the docs and give you an extended opion afterwards.

Thanks :smiley: 

> Also my `eslint-fix` is reporting 129 problems. This should be fixed before merge.

Yes, I think we should fix all projects now and create a PR in each one for the fixes.

**Comment by tim-kilian** [comment]
> Yes, I think we should fix all projects now and create a PR in each one for the fixes.

great idea, I'll create some issues for this.

**Comment by 0x4d** [comment]
> I'll create some issues for this.

Thanks! Let's first merge all other open (non-WIP) stuff so that everything will be clean in the end.

**Comment by tim-kilian** [comment]
I've also created a global issue for this, which links all sub issues. renew-js/renew-js#20

**Pull request merged**
